### ISSUE TITLE
Example file missing

### ISSUE THREAD

**Issue by polyakoff** [IDRSolutions/maven-OpenViewerFX-src#2]
At
maven-OpenViewerFX-src/OpenViewerFX/src/main/java/org/jpedal/examples/viewer/OpenViewerFX.java

at the very beggining

```java
 * <p>If you want to implement your own there is
 * a very simple example at : 
 * <a href="http://files.idrsolutions.com/samplecode/org/jpedal/examples/baseviewer/BaseOpenViewerFX.java.html">BaseOpenViewerFX Demo</a>
 * <p>We recommend you look at the full viewer as it is totally configurable and does everything for you.</p>
 * 
 */
```
I get error 404 trying to access the  example file. Could you point me where to find it?

**Comment by IDRSolutions** [comment]
> On 6 Jan 2016, at 07:36, polyakoff <notifications@github.com> wrote:
> 
> If you want to implement your own there

It is http://files.idrsolutions.com/samplecode/org/jpedal/examples/baseviewer/BaseViewerFX.java.html

I would recommend using the source inside the actual src you can download with OpenViewerFX.

Regards,

MArk

**Comment by polyakoff** [comment]
Thanks for fast response!

**Comment by shishifanbuxie** [comment]
I clone this reopsitory and run the code use [http://files.idrsolutions.com/samplecode/org/jpedal/examples/baseviewer/BaseViewerFX.java.html](url)

i get e exception 
```java 
/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=57987:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/tools.jar:/Users/shishifanbuxie/IdeaWorkSpace/maven-OpenViewerFX-src/OpenViewerFX/target/classes:/Users/shishifanbuxie/maven/repository/org/eclipse/birt/runtime/3_7_1/org.mozilla.javascript/1.7.2/org.mozilla.javascript-1.7.2.jar:/Users/shishifanbuxie/maven/repository/bouncycastle/bcprov-jdk16/140/bcprov-jdk16-140.jar:/Users/shishifanbuxie/maven/repository/bouncycastle/bcmail-jdk16/140/bcmail-jdk16-140.jar org.jpedal.examples.baseviewer.BaseViewerFX
objc[12131]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java (0x1010964c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1011724e0). One of the two will be used. Which one is undefined.
JAVA VERSION : 1.8
java.lang.ClassCastException: org.jpedal.objects.acroforms.actions.EmptyActionHandler$1 cannot be cast to javafx.event.EventHandler
	at org.jpedal.objects.acroforms.javafx.JavaFXFormFactory.setupButton(JavaFXFormFactory.java:1273)
	at org.jpedal.objects.acroforms.javafx.JavaFXFormFactory.setupAnnotationButton(JavaFXFormFactory.java:95)
	at org.jpedal.objects.acroforms.javafx.JavaFXFormFactory.annotationButton(JavaFXFormFactory.java:393)
	at org.jpedal.objects.acroforms.GUIData.resolveGUIComponent(GUIData.java:175)
	at org.jpedal.objects.acroforms.GUIData.checkGUIObjectResolved(GUIData.java:147)
	at org.jpedal.objects.acroforms.GUIData.displayComponents(GUIData.java:298)
	at org.jpedal.objects.acroforms.AcroRenderer.displayComponentsOnscreen(AcroRenderer.java:1137)
	at org.jpedal.display.javafx.SingleDisplayFX.addForms(SingleDisplayFX.java:285)
	at org.jpedal.display.javafx.SingleDisplayFX.paintPage(SingleDisplayFX.java:264)
	at org.jpedal.display.javafx.SingleDisplayFX.refreshDisplay(SingleDisplayFX.java:103)
	at org.jpedal.PdfDecoderFX.decodePage(PdfDecoderFX.java:1097)
	at org.jpedal.examples.baseviewer.BaseViewerFX.decodePage(BaseViewerFX.java:769)
	at org.jpedal.examples.baseviewer.BaseViewerFX.goToPage(BaseViewerFX.java:830)
	at org.jpedal.examples.baseviewer.BaseViewerFX.openFile(BaseViewerFX.java:651)
	at org.jpedal.examples.baseviewer.BaseViewerFX.loadPDF(BaseViewerFX.java:557)
	at org.jpedal.examples.baseviewer.BaseViewerFX$7$1.run(BaseViewerFX.java:393)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: org.jpedal.objects.acroforms.actions.EmptyActionHandler$1 cannot be cast to javafx.event.EventHandler
	at org.jpedal.objects.acroforms.javafx.JavaFXFormFactory.setupButton(JavaFXFormFactory.java:1273)
	at org.jpedal.objects.acroforms.javafx.JavaFXFormFactory.setupAnnotationButton(JavaFXFormFactory.java:95)
	at org.jpedal.objects.acroforms.javafx.JavaFXFormFactory.annotationButton(JavaFXFormFactory.java:393)
	at org.jpedal.objects.acroforms.GUIData.resolveGUIComponent(GUIData.java:175)
	at org.jpedal.objects.acroforms.GUIData.checkGUIObjectResolved(GUIData.java:147)
	at org.jpedal.objects.acroforms.GUIData.displayComponents(GUIData.java:298)
	at org.jpedal.objects.acroforms.AcroRenderer.displayComponentsOnscreen(AcroRenderer.java:1137)
	at org.jpedal.display.javafx.SingleDisplayFX.addForms(SingleDisplayFX.java:285)
	at org.jpedal.display.javafx.SingleDisplayFX.paintPage(SingleDisplayFX.java:264)
	at org.jpedal.display.javafx.SingleDisplayFX.refreshDisplay(SingleDisplayFX.java:103)
	at org.jpedal.display.GUIDisplay.setPageRotation(GUIDisplay.java:766)
	at org.jpedal.display.javafx.SingleDisplayFX.setPageRotation(SingleDisplayFX.java:131)
	at org.jpedal.PdfDecoderFX.setPageParameters(PdfDecoderFX.java:955)
	at org.jpedal.examples.baseviewer.BaseViewerFX.fitToX(BaseViewerFX.java:728)
	at org.jpedal.examples.baseviewer.BaseViewerFX.fitToX(BaseViewerFX.java:704)
	at org.jpedal.examples.baseviewer.BaseViewerFX.decodePage(BaseViewerFX.java:776)
	at org.jpedal.examples.baseviewer.BaseViewerFX.goToPage(BaseViewerFX.java:830)
	at org.jpedal.examples.baseviewer.BaseViewerFX.openFile(BaseViewerFX.java:651)
	at org.jpedal.examples.baseviewer.BaseViewerFX.loadPDF(BaseViewerFX.java:557)
	at org.jpedal.examples.baseviewer.BaseViewerFX$7$1.run(BaseViewerFX.java:393)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```
